breeds = {
    1: "Abyssinian",
    2: "American_Bulldog",
    3: "American_Pit_Bull_Terrier",
    4: "Basset_Hound",
    5: "Beagle",
    6: "Bengal",
    7: "Birman",
    8: "Bombay",
    9: "Boxer",
    10: "British_Shorthair",
    11: "Chihuahua",
    12: "Egyptian_Mau",
    13: "English_Cocker_Spaniel",
    14: "English_Setter",
    15: "German_Shorthaired",
    16: "Great_Pyrenees",
    17: "Havanese",
    18: "Japanese_Chin",
    19: "Keeshond",
    20: "Leonberger",
    21: "Maine_Coon",
    22: "Miniature_Pinscher",
    23: "Newfoundland",
    24: "Persian",
    25: "Pomeranian",
    26: "Pug",
    27: "Ragdoll",
    28: "Russian_Blue",
    29: "Saint_Bernard",
    30: "Samoyed",
    31: "Scottish_Terrier",
    32: "Shiba_Inu",
    33: "Siamese",
    34: "Sphynx",
    35: "Staffordshire_Bull_Terrier",
    36: "Wheaten_Terrier",
    37: "Yorkshire_Terrier"
}

cat_breeds = {
    1: "Abyssinian",
    6: "Bengal",
    7: "Birman",
    8: "Bombay",
    10: "British_Shorthair",
    12: "Egyptian_Mau",
    21: "Maine_Coon",
    24: "Persian",
    27: "Ragdoll",
    28: "Russian_Blue",
    33: "Siamese",
    34: "Sphynx"
}

dog_breeds = {
    2: "American_Bulldog",
    3: "American_Pit_Bull_Terrier",
    4: "Basset_Hound",
    5: "Beagle",
    9: "Boxer",
    11: "Chihuahua",
    13: "English_Cocker_Spaniel",
    14: "English_Setter",
    15: "German_Shorthaired",
    16: "Great_Pyrenees",
    17: "Havanese",
    18: "Japanese_Chin",
    19: "Keeshond",
    20: "Leonberger",
    22: "Miniature_Pinscher",
    23: "Newfoundland",
    25: "Pomeranian",
    26: "Pug",
    29: "Saint_Bernard",
    30: "Samoyed",
    31: "Scottish_Terrier",
    32: "Shiba_Inu",
    35: "Staffordshire_Bull_Terrier",
    36: "Wheaten_Terrier",
    37: "Yorkshire_Terrier"
}
